# Schur Decomposition

In [15]:
# Credit: Code snippet inspired by https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.schur.html
# Additional code and comments have been added for clearer explanation

import numpy as np  # For matrix multiplication
from scipy.linalg import schur  # Schur decomposition package

np.set_printoptions(2) # Print all floats to 2 significant figures, and suppresses scientific notation

A = np.array([[0, 2, 2], [0, 1, 2], [1, 0, 1]]) # 3x3 matrix
T, Z = schur(A) # A = Z * T * Z^H

"""
Explanation:

1) np.asmatrix(Z) converts the numpy ndarray Z into a numpy matrix
    -> The reason we did this is to get access to the .getH() method of the numpy matrix class

2) numpy.matrix.getH()
    -> Returns the conjugate transpose of the matrix
    -> For matrices with only real values, .getH() simply returns the transpose of the matrix
"""
ZT = np.matmul(Z, T)
ZH = np.asmatrix(Z).getH()
ZTZH = np.matmul(ZT, ZH)

# Print out the results
print(f"Z = \n{Z}\n")
print(f"T = \n{T}\n")
print(f"Z^H = \n{ZH}\n")
print("^^^ Observe how Z^H is the transpose of Z in this case (since Z only has real values) ^^^\n")
print(f"Z * T * Z^H = \n{ZTZH}\n")
print(f"A = \n{A}\n")
print("^^^ Z * T * Z^H is almost equal to A (due to limitations in floating point precision) ^^^")

Z = 
[[ 0.73 -0.6   0.33]
 [ 0.53  0.8   0.29]
 [ 0.44  0.04 -0.9 ]]

T = 
[[ 2.66  1.42 -1.93]
 [ 0.   -0.33 -0.49]
 [ 0.    1.31 -0.33]]

Z^H = 
[[ 0.73  0.53  0.44]
 [-0.6   0.8   0.04]
 [ 0.33  0.29 -0.9 ]]

^^^ Observe how Z^H is the transpose of Z in this case (since Z only has real values) ^^^

Z * T * Z^H = 
[[-8.21e-16  2.00e+00  2.00e+00]
 [-4.00e-16  1.00e+00  2.00e+00]
 [ 1.00e+00  1.49e-17  1.00e+00]]

A = 
[[0 2 2]
 [0 1 2]
 [1 0 1]]

^^^ Z * T * Z^H is almost equal to A (due to limitations in floating point precision) ^^^


# QR Factorization

In [16]:
# Credit: Code snippet inspired by https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html
# Additional code and comments have been added for clearer explanation

import numpy as np

np.set_printoptions(2)  # Print all floats to 2 significant figures, and suppresses scientific notation

rng = np.random.default_rng()  # Sets up random number generator

A = rng.normal(size=(4, 4))  # 4x4 matrix, where each number is drawn from a normal distribution
Q, R = np.linalg.qr(A)  # A = Q * R
QR = np.matmul(Q, R)

print(f"Q = \n{Q}\n")
print(f"R = \n{R}\n")
print("^^^ Notice how R is upper triangular ^^^\n")
print(f"Q * R = \n{QR}\n")
print(f"A = \n{A}\n")
print("^^^ Q * R is almost equal to A (due to limitations in floating point precision) ^^^")

Q = 
[[-0.49 -0.26  0.74 -0.38]
 [-0.2  -0.66  0.01  0.72]
 [-0.78  0.53 -0.19  0.26]
 [ 0.33  0.47  0.65  0.51]]

R = 
[[ 1.72 -1.11 -0.39  0.27]
 [ 0.    1.82 -0.99 -0.36]
 [ 0.    0.    0.11 -1.61]
 [ 0.    0.    0.   -0.2 ]]

^^^ Notice how R is upper triangular ^^^

Q * R = 
[[-0.83  0.06  0.53 -1.15]
 [-0.35 -0.97  0.73  0.03]
 [-1.35  1.83 -0.24 -0.15]
 [ 0.57  0.48 -0.52 -1.22]]

A = 
[[-0.83  0.06  0.53 -1.15]
 [-0.35 -0.97  0.73  0.03]
 [-1.35  1.83 -0.24 -0.15]
 [ 0.57  0.48 -0.52 -1.22]]

^^^ Q * R is almost equal to A (due to limitations in floating point precision) ^^^


# Cholesky Decomposition

In [1]:
import numpy as np

A = np.matrix([[25, 15, -5], [15, 18, 0], [-5, 0, 11]])
L = np.linalg.cholesky(A)
LT = L.transpose()
LLT = np.matmul(L, LT)

print(f"L = \n{L}\n")
print(f"L^T = \n{LT}\n")
print("^^^ Notice how L is lower-triangular and its transpose is upper-triangular^^^\n")
print(f"L * L^T = \n{LLT}\n")
print(f"A = \n{A}\n")
print("^^^ L * L^T is almost equal to A (due to limitations in floating point precision) ^^^")

# Note how Cholesky decomposition does not work on non-positive-definite matrices (THIS WILL THROW AN ERROR)
B = np.matrix([[1, 1, -1], [-1, -2, 0], [5, 0, -11]])
L = np.linalg.cholesky(B)

L = 
[[ 5.  0.  0.]
 [ 3.  3.  0.]
 [-1.  1.  3.]]

L^T = 
[[ 5.  3. -1.]
 [ 0.  3.  1.]
 [ 0.  0.  3.]]

^^^ Notice how L is lower-triangular and its transpose is upper-triangular^^^

L * L^T = 
[[25. 15. -5.]
 [15. 18.  0.]
 [-5.  0. 11.]]

A = 
[[25 15 -5]
 [15 18  0]
 [-5  0 11]]

^^^ L * L^T is almost equal to A (due to limitations in floating point precision) ^^^


LinAlgError: Matrix is not positive definite